### ISSUE TITLE
./get_deps.py: "IOError: [Errno 2] No such file or directory: '/mingw64/bin/libgcc_s_seh-1.dll'"

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu#62]
I have not seen this happen on AppVeyor CI yet, which suggests this is environment specific.

It's quite bad because this happens at the end of compilation, so it looks like XQEMU compilation has failed, despite having worked fine.

**Environment**

I'm running 0523deaa938dd267a17bcc5102a49dd58ebffe79 with #56 and #61, but had the same issue happen without those 2 PRs added.
My system is Windows 10 Pro N 64-bit (10.0, Build 17133).
MSYS2 has been upgraded to latest version using `pacman -Syu`

**Package versions**

```
$ pacman -Qs mingw-w64-x86_64-toolchain && pacman -Qs python2 && pacman -Qs python3
local/mingw-w64-x86_64-binutils 2.30-4 (mingw-w64-x86_64-toolchain)
    A set of programs to assemble and manipulate binary and object files (mingw-w64)
local/mingw-w64-x86_64-crt-git 6.0.0.5144.45e00853-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 CRT for Windows
local/mingw-w64-x86_64-gcc 7.3.0-2 (mingw-w64-x86_64-toolchain)
    GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
local/mingw-w64-x86_64-gcc-libgfortran 7.3.0-2 (mingw-w64-x86_64-toolchain)
    GNU Compiler Collection (libgfortran) for MinGW-w64
local/mingw-w64-x86_64-gcc-libs 7.3.0-2 (mingw-w64-x86_64-toolchain)
    GNU Compiler Collection (libraries) for MinGW-w64
local/mingw-w64-x86_64-gdb 8.1-2 (mingw-w64-x86_64-toolchain)
    GNU Debugger (mingw-w64)
local/mingw-w64-x86_64-headers-git 6.0.0.5144.45e00853-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 headers for Windows
local/mingw-w64-x86_64-libmangle-git 6.0.0.5079.3b7a42fd-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 libmangle
local/mingw-w64-x86_64-libwinpthread-git 6.0.0.5134.2416de71-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 winpthreads library
local/mingw-w64-x86_64-make 4.2.1-2 (mingw-w64-x86_64-toolchain)
    GNU make utility to maintain groups of programs (mingw-w64)
local/mingw-w64-x86_64-pkg-config 0.29.2-1 (mingw-w64-x86_64-toolchain)
    A system for managing library compile/link flags (mingw-w64)
local/mingw-w64-x86_64-tools-git 6.0.0.5111.3bc5ab74-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 tools
local/mingw-w64-x86_64-winpthreads-git 6.0.0.5134.2416de71-1 (mingw-w64-x86_64-toolchain)
    MinGW-w64 winpthreads library
local/mingw-w64-x86_64-pyqt5-common 5.10.1-1
    Common PyQt files shared between python3-pyqt5 and python2-pyqt5
local/mingw-w64-x86_64-python2 2.7.15-1
    A high-level scripting language (mingw-w64)
local/mingw-w64-x86_64-python2-pyqt5 5.10.1-1
    A set of Python 2.x bindings for the Qt5 toolkit
local/mingw-w64-x86_64-python2-sip 4.19.9-1
    Python 2.x SIP bindings for C and C++ libraries (mingw-w64)
local/python2 2.7.15-2
    A high-level scripting language
local/mingw-w64-x86_64-pyqt5-common 5.10.1-1
    Common PyQt files shared between python3-pyqt5 and python2-pyqt5
local/mingw-w64-x86_64-python3 3.6.5-1
    A high-level scripting language (mingw-w64)
local/mingw-w64-x86_64-python3-pyqt5 5.10.1-1
    A set of Python 3.x bindings for the Qt5 toolkit
local/mingw-w64-x86_64-python3-sip 4.19.9-1
    Python 3.x SIP bindings for C and C++ libraries (mingw-w64)
local/python 3.6.6-1
    Next generation of the python high-level scripting language
local/python3-appdirs 1.4.3-2
    A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
local/python3-packaging 16.8-3
    Core utilities for Python packages
local/python3-pip 10.0.1-1
    The PyPA recommended tool for installing Python packages
local/python3-pyparsing 2.2.0-2
    General parsing module for Python
local/python3-setuptools 39.2.0-1
    Easily download, build, install, upgrade, and uninstall Python packages
local/python3-six 1.10.0-5
    Python 2 and 3 compatibility utilities
```

**Detailed log**

Running `./build_windows.sh` results in errors in dependency collection phase:

```
+ python2 ./get_deps.py dist/xqemu.exe dist
Skipping system DLL /c/WINDOWS/SYSTEM32/ntdll.dll
Skipping system DLL /c/WINDOWS/System32/KERNEL32.DLL
Skipping system DLL /c/WINDOWS/System32/KERNELBASE.dll
Skipping system DLL /c/WINDOWS/System32/ADVAPI32.dll
Skipping system DLL /c/WINDOWS/System32/msvcrt.dll
Skipping system DLL /c/WINDOWS/System32/sechost.dll
Skipping system DLL /c/WINDOWS/System32/RPCRT4.dll
Skipping system DLL /c/WINDOWS/System32/GDI32.dll
Skipping system DLL /c/WINDOWS/System32/gdi32full.dll
Skipping system DLL /c/WINDOWS/System32/msvcp_win.dll
Skipping system DLL /c/WINDOWS/System32/ucrtbase.dll
Skipping system DLL /c/WINDOWS/System32/USER32.dll
Skipping system DLL /c/WINDOWS/System32/win32u.dll
Skipping system DLL /c/WINDOWS/System32/ole32.dll
Skipping system DLL /c/WINDOWS/System32/combase.dll
Skipping system DLL /c/WINDOWS/SYSTEM32/IPHLPAPI.DLL
Skipping system DLL /c/WINDOWS/System32/bcryptPrimitives.dll
Skipping system DLL /c/WINDOWS/System32/SHELL32.dll
Skipping system DLL /c/WINDOWS/System32/cfgmgr32.dll
Skipping system DLL /c/WINDOWS/SYSTEM32/OPENGL32.dll
Skipping system DLL /c/WINDOWS/System32/shcore.dll
Skipping system DLL /c/WINDOWS/SYSTEM32/GLU32.dll
Skipping system DLL /c/WINDOWS/System32/windows.storage.dll
Skipping system DLL /c/WINDOWS/System32/shlwapi.dll
Skipping system DLL /c/WINDOWS/System32/kernel.appcore.dll
Skipping system DLL /c/WINDOWS/System32/profapi.dll
Skipping system DLL /c/WINDOWS/System32/powrprof.dll
Skipping system DLL /c/WINDOWS/System32/FLTLIB.DLL
Skipping system DLL /c/WINDOWS/System32/WS2_32.dll
Skipping system DLL /c/WINDOWS/SYSTEM32/WINMM.dll
Copying /mingw64/bin/libssp-0.dll...
Traceback (most recent call last):
  File "./get_deps.py", line 40, in <module>
    main()
  File "./get_deps.py", line 37, in main
    shutil.copyfile(dll_path, os.path.join(args.dest, dll_name))
  File "C:/msys64/mingw64/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/mingw64/bin/libssp-0.dll'
```

Re-running (`./build_windows.sh`) gives:

```
...
Skipping system DLL /c/WINDOWS/System32/powrprof.dll
Skipping system DLL /c/WINDOWS/System32/FLTLIB.DLL
Skipping system DLL /c/WINDOWS/System32/WS2_32.dll
Skipping system DLL /c/WINDOWS/SYSTEM32/WINMM.dll
Copying /mingw64/bin/libgcc_s_seh-1.dll...
Traceback (most recent call last):
  File "./get_deps.py", line 40, in <module>
    main()
  File "./get_deps.py", line 37, in main
    shutil.copyfile(dll_path, os.path.join(args.dest, dll_name))
  File "C:/msys64/mingw64/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/mingw64/bin/libgcc_s_seh-1.dll'
```

**Notes**

Running more often seems to get '/mingw64/bin/libgcc_s_seh-1.dll' again, although I'm not sure - I only ran this about 5 times as each build takes a considerable amount of time on this machine. Could be that it still randomly returns the other dll too (maybe others too).

**Comment by mborgerson** [comment]
My guess is that you're running native Python for Windows. Can you confirm `which python` in your msys shell?

**Comment by JayFoxRox** [comment]
I also checked `which` for `python`, `python2` and `python3` - all part of MSYS.
